/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.edu.ec.vista;

import java.util.List;
import ups.edu.ec.controlador.ControladorNovia;
import ups.edu.ec.controlador.ControladorNovio;
import ups.edu.ec.modelo.Novia;
import ups.edu.ec.modelo.Novio;
import ups.edu.ec.modelo.Usuario;

/**
 *
 * @author user
 */
public class VentanaVerCasados extends javax.swing.JInternalFrame {
    private ControladorNovio controladorNovio;
    private ControladorNovia controladorNovia;
    private List<Novio> lista;
    private List<Novia> listaa;
    /**
     * Creates new form VentanaVerCasados
     */
    public VentanaVerCasados(ControladorNovio controladorNovio,ControladorNovia controladorNovia) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        botonVerNovio = new javax.swing.JButton();
        botonVerNovia = new javax.swing.JButton();

        setClosable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        botonVerNovio.setText("VerCasado");
        botonVerNovio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerNovioActionPerformed(evt);
            }
        });

        botonVerNovia.setText("VerCasada");
        botonVerNovia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerNoviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVerNovia)
                .addGap(18, 18, 18)
                .addComponent(botonVerNovio)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerNovio)
                    .addComponent(botonVerNovia))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerNovioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerNovioActionPerformed
       lista=controladorNovio.getLista();
        for (int i = 0; i < lista.size(); i++) {
            jTextArea1.setText(lista.get(i).toString());
        }
    }//GEN-LAST:event_botonVerNovioActionPerformed

    private void botonVerNoviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerNoviaActionPerformed
        listaa=controladorNovia.getLista();
        for (int i = 0; i < lista.size(); i++) {
            jTextArea1.setText(lista.get(i).toString());
        }
    }//GEN-LAST:event_botonVerNoviaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerNovia;
    private javax.swing.JButton botonVerNovio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
